// <auto-generated />
using Curiosity_Voyage_Library_Management_System_1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Curiosity_Voyage_Library_Management_System_1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241210210249_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Curiosity_Voyage_Library_Management_System_1.Models.BookBorrower", b =>
                {
                    b.Property<int>("BooksID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BorrowersID")
                        .HasColumnType("INTEGER");

                    b.HasKey("BooksID", "BorrowersID");

                    b.HasIndex("BorrowersID");

                    b.ToTable("BookBorrower");
                });

            modelBuilder.Entity("Curiosity_Voyage_Library_Management_System_1.Models.Books", b =>
                {
                    b.Property<int>("BooksID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("BooksID");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Curiosity_Voyage_Library_Management_System_1.Models.Borrowers", b =>
                {
                    b.Property<int>("BorrowersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("BorrowersID");

                    b.ToTable("Borrowers");
                });

            modelBuilder.Entity("Curiosity_Voyage_Library_Management_System_1.Models.BookBorrower", b =>
                {
                    b.HasOne("Curiosity_Voyage_Library_Management_System_1.Models.Books", "Books")
                        .WithMany("BookBorrowers")
                        .HasForeignKey("BooksID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Curiosity_Voyage_Library_Management_System_1.Models.Borrowers", "Borrowers")
                        .WithMany("BookBorrowers")
                        .HasForeignKey("BorrowersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Books");

                    b.Navigation("Borrowers");
                });

            modelBuilder.Entity("Curiosity_Voyage_Library_Management_System_1.Models.Books", b =>
                {
                    b.Navigation("BookBorrowers");
                });

            modelBuilder.Entity("Curiosity_Voyage_Library_Management_System_1.Models.Borrowers", b =>
                {
                    b.Navigation("BookBorrowers");
                });
#pragma warning restore 612, 618
        }
    }
}
